#!/usr/bin/env python3
"""db_schema.py — schema dump for engines usql cannot introspect safely (DB2, Oracle).

Why this exists
---------------
`db.sh` drives everything through `usql`. That works for MySQL/Postgres/SQLite/MSSQL,
but IBM Db2 is only reachable from usql through ODBC, and that path is *measurably*
unsafe for the one thing this project needs -- reading the system catalog. See README
("usql + ODBC 의 한계"). Rather than ship a path that silently truncates a schema
cache, Db2 goes through its native driver here.

Design, same as the rest of the project
---------------------------------------
1. No MCP. A CLI you call; zero idle token cost.
2. The schema is written to a *file* so it can be grepped a line at a time.
3. Credentials come from the connection profile only -- never from argv, never
   printed, never written into the dump.

Output is one-line DDL, in the same file `db.sh` already uses
(`~/.claude/db/schema/<alias>.schema.sql`), so `db.sh tables|desc|search` keep working.

Install the driver you need:
    pip install ibm_db      # Db2   (bundles the IBM CLI driver -- no separate install)
    pip install oracledb    # Oracle (thin mode -- no Oracle client needed)

Usage:
    db_schema.py test  <alias>
    db_schema.py query <alias> "<sql>" [table|csv|json]
    db_schema.py dump  <alias>
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import time
from pathlib import Path

DB_DIR = Path(os.environ.get("DB_DIR") or (Path.home() / ".claude" / "db"))
SCHEMA_DIR = DB_DIR / "schema"

# Catalog schemas that belong to the engine, not to the user.
DB2_SYS = ("TABSCHEMA NOT LIKE 'SYS%' AND TABSCHEMA NOT IN "
           "('NULLID','SQLJ','DB2GSE','DB2QP','SQLLOGGING')")
ORA_SYS = ("owner NOT IN ('SYS','SYSTEM','XDB','MDSYS','CTXSYS','OUTLN','DBSNMP',"
           "'ORDSYS','ORDDATA','OLAPSYS','WMSYS','LBACSYS','APPQOSSYS','AUDSYS',"
           "'GSMADMIN_INTERNAL','DVSYS','DVF','ORDPLUGINS','SI_INFORMTN_SCHEMA')")

HEADER = """\
-- Generated by db_schema.py -- do NOT edit by hand. `db.sh refresh {alias}` overwrites it.
--
-- Format: one line per object, so `db.sh tables|desc|search` can grep a single line.
--   CREATE TABLE  ...  a real table
--   CREATE VIEW   ...  a view. Only its column signature and dependencies are captured,
--                      NOT the SELECT body -- do not read it as executable DDL.
--   CREATE INDEX  ...  index, in column order (DESC is preserved where the engine reports it)
--   COMMENT ON    ...  table/column comments
--
-- `?` means "the catalog did not tell us", NOT "there is none". A privilege-restricted
-- account produces `?` for indexes and comments while tables still read fine.
"""


# ----------------------------------------------------------------- profile
def load_profile(alias: str) -> dict:
    """Read `~/.claude/db/*.env` the same way db.sh does: match on DB_ALIAS."""
    if not DB_DIR.is_dir():
        sys.exit(f"ERROR: profile directory not found: {DB_DIR}")
    for f in sorted(DB_DIR.glob("*.env")):
        kv = {}
        for line in f.read_text(encoding="utf-8").splitlines():
            m = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
            if m:
                kv[m.group(1)] = m.group(2).strip().strip('"').strip("'")
        if kv.get("DB_ALIAS") == alias:
            kv["_file"] = str(f)
            return kv
    sys.exit(f"ERROR: alias '{alias}' not found in {DB_DIR}")


def safe_dsn(p: dict) -> str:
    """Display form -- never includes the password (mirrors db.sh CONN_STR_SAFE)."""
    return f"{p['DB_TYPE']}://{p.get('DB_USER', '')}@{p.get('DB_HOST', '')}:{p.get('DB_PORT', '')}/{p.get('DB_NAME', '')}"


# ----------------------------------------------------------------- engines
class Db2:
    ping_sql = "SELECT 1 FROM SYSIBM.SYSDUMMY1"
    driver = "ibm_db_dbi"

    @staticmethod
    def connect(p: dict):
        try:
            import ibm_db_dbi
        except ImportError:
            sys.exit("ERROR: ibm_db not installed. Run: pip install ibm_db")
        dsn = (f"DATABASE={p['DB_NAME']};HOSTNAME={p['DB_HOST']};PORT={p['DB_PORT']};"
               f"PROTOCOL=TCPIP;UID={p['DB_USER']};PWD={p['DB_PASS']};")
        return ibm_db_dbi.connect(dsn, "", "")

    objects = (f"SELECT TABSCHEMA, TABNAME, TYPE, REMARKS FROM SYSCAT.TABLES "
               f"WHERE TYPE IN ('T','V') AND {DB2_SYS} ORDER BY TABSCHEMA, TABNAME")
    columns = (f"SELECT TABSCHEMA, TABNAME, COLNAME, TYPENAME, LENGTH, SCALE, NULLS, "
               f"KEYSEQ, REMARKS, CAST(NULL AS INTEGER) FROM SYSCAT.COLUMNS "
               f"WHERE {DB2_SYS} ORDER BY TABSCHEMA, TABNAME, COLNO")
    indexes = (f"SELECT TABSCHEMA, TABNAME, INDNAME, UNIQUERULE, COLNAMES "
               f"FROM SYSCAT.INDEXES WHERE {DB2_SYS} ORDER BY TABSCHEMA, TABNAME, INDNAME")
    viewdeps = (f"SELECT TABSCHEMA, TABNAME, BSCHEMA, BNAME FROM SYSCAT.TABDEP "
                f"WHERE DTYPE='V' AND BTYPE IN ('T','V') AND {DB2_SYS} "
                f"ORDER BY TABSCHEMA, TABNAME, BSCHEMA, BNAME")
    pk = None        # Db2 gives key position in SYSCAT.COLUMNS.KEYSEQ
    idxcols = None   # ...and index column order in SYSCAT.INDEXES.COLNAMES

    @staticmethod
    def fmt_type(row) -> str:
        t, length, scale = (row[3] or "?").strip(), int(row[4] or 0), int(row[5] or 0)
        if t in ("DECIMAL", "NUMERIC"):
            return f"{t}({length},{scale})"
        if t in ("CHARACTER", "VARCHAR", "GRAPHIC", "VARGRAPHIC", "BLOB", "CLOB", "DBCLOB"):
            return f"{t}({length})"
        if t == "TIMESTAMP":
            return f"{t}({scale})"
        return t

    @staticmethod
    def split_index_cols(colnames: str) -> list[str]:
        """Db2 encodes order and direction as `+COL-COL2`."""
        raw = (colnames or "").strip()
        out, cur, sign = [], "", ""
        for ch in raw:
            if ch in "+-":
                if cur:
                    out.append(f'"{cur}"' + (" DESC" if sign == "-" else ""))
                cur, sign = "", ch
            else:
                cur += ch
        if cur:
            out.append(f'"{cur}"' + (" DESC" if sign == "-" else ""))
        return out


class Oracle:
    ping_sql = "SELECT 1 FROM DUAL"
    driver = "oracledb (thin)"

    @staticmethod
    def connect(p: dict):
        try:
            import oracledb
        except ImportError:
            sys.exit("ERROR: oracledb not installed. Run: pip install oracledb")
        # DB_NAME carries the service name for Oracle profiles.
        return oracledb.connect(user=p["DB_USER"], password=p["DB_PASS"],
                                dsn=f"{p['DB_HOST']}:{p['DB_PORT']}/{p['DB_NAME']}")

    objects = (f"SELECT owner, table_name, otype, comments FROM ("
               f" SELECT t.owner, t.table_name, t.otype, c.comments"
               f" FROM all_tab_comments c RIGHT JOIN ("
               f"   SELECT owner, table_name, 'T' AS otype FROM all_tables"
               f"   UNION ALL SELECT owner, view_name, 'V' FROM all_views) t"
               f" ON c.owner = t.owner AND c.table_name = t.table_name)"
               f" WHERE {ORA_SYS} ORDER BY owner, table_name")
    columns = (f"SELECT c.owner, c.table_name, c.column_name, c.data_type,"
               f" c.data_length, c.data_scale, c.nullable, NULL, cc.comments,"
               f" c.data_precision"
               f" FROM all_tab_columns c LEFT JOIN all_col_comments cc"
               f"   ON cc.owner=c.owner AND cc.table_name=c.table_name"
               f"  AND cc.column_name=c.column_name"
               f" WHERE c.{ORA_SYS} ORDER BY c.owner, c.table_name, c.column_id")
    indexes = (f"SELECT table_owner, table_name, index_name, uniqueness, NULL"
               f" FROM all_indexes WHERE {ORA_SYS.replace('owner NOT IN', 'table_owner NOT IN', 1)}"
               f" ORDER BY table_owner, table_name, index_name")
    viewdeps = (f"SELECT owner, name, referenced_owner, referenced_name"
                f" FROM all_dependencies WHERE type='VIEW'"
                f" AND referenced_type IN ('TABLE','VIEW') AND {ORA_SYS}"
                f" ORDER BY owner, name, referenced_owner, referenced_name")
    # Oracle keeps primary keys in the constraint views, not in all_tab_columns.
    # Reading `pk = none` off all_tab_columns would report "no primary key" for every
    # table, which is a false statement -- so we ask the right view instead.
    pk = (f"SELECT c.owner, c.table_name, cc.column_name, cc.position"
          f" FROM all_constraints c JOIN all_cons_columns cc"
          f"   ON cc.owner=c.owner AND cc.constraint_name=c.constraint_name"
          f" WHERE c.constraint_type='P' AND c.{ORA_SYS}"
          f" ORDER BY c.owner, c.table_name, cc.position")
    idxcols = (f"SELECT table_owner, table_name, index_name, column_name,"
               f" column_position, descend FROM all_ind_columns"
               f" WHERE {ORA_SYS.replace('owner NOT IN', 'table_owner NOT IN', 1)}"
               f" ORDER BY table_owner, table_name, index_name, column_position")

    @staticmethod
    def fmt_type(row) -> str:
        t, length, scale = (row[3] or "?").strip(), int(row[4] or 0), int(row[5] or 0)
        prec = row[9] if len(row) > 9 else None
        if t == "NUMBER":
            # data_length is the 22-byte storage width, not the precision. Writing
            # NUMBER(22,0) for a NUMBER(10) column would be a confident wrong answer.
            if prec in (None, ""):
                return "NUMBER" if not scale else f"NUMBER(*,{scale})"
            return f"NUMBER({int(prec)},{scale})"
        if t.startswith(("VARCHAR", "CHAR", "NVARCHAR", "NCHAR", "RAW")):
            return f"{t}({length})"
        return t

    @staticmethod
    def split_index_cols(colnames: str) -> list[str]:
        return []


ENGINES = {"db2": Db2, "oracle": Oracle}


# ----------------------------------------------------------------- read
def rows(cur, sql):
    """Return (rows, ok). A failed catalog read is reported, never silently empty."""
    if sql is None:
        return [], True
    try:
        cur.execute(sql)
        return [tuple(r) for r in cur.fetchall()], True
    except Exception as e:                                    # noqa: BLE001
        print(f"WARN: catalog query failed -> values become '?': "
              f"{type(e).__name__}: {e}", file=sys.stderr)
        return [], False


def s(v) -> str:
    return "" if v is None else str(v).strip()


def q(*parts) -> str:
    return ".".join(f'"{p}"' for p in parts)


def esc(v: str) -> str:
    return v.replace("'", "''")


# ----------------------------------------------------------------- render
def render(eng, data, alias: str, prof: dict) -> tuple[list[str], int, int]:
    by_col, by_idx, by_dep, by_pk, by_ixc = {}, {}, {}, {}, {}
    for r in data["columns"]:
        by_col.setdefault((s(r[0]), s(r[1])), []).append(r)
    for r in data["indexes"]:
        by_idx.setdefault((s(r[0]), s(r[1])), []).append(r)
    for r in data["viewdeps"]:
        by_dep.setdefault((s(r[0]), s(r[1])), []).append(r)
    for r in data["pk"]:
        by_pk.setdefault((s(r[0]), s(r[1])), {})[s(r[2])] = int(r[3] or 0)
    for r in data["idxcols"]:
        d = " DESC" if s(r[5]).upper().startswith("DESC") else ""
        by_ixc.setdefault((s(r[0]), s(r[1]), s(r[2])), []).append(
            (int(r[4] or 0), f'"{s(r[3])}"' + d))

    out = [f"-- {alias} ({safe_dsn(prof)}) @{time.strftime('%Y-%m-%d')}", HEADER]
    unread = sorted(k for k, v in data["ok"].items() if not v)
    if unread:
        # The warning on stderr scrolls away; whoever greps this file months from now
        # must still be able to tell "not present" from "not readable".
        out.append(f"-- INCOMPLETE: these catalogs could not be read: {', '.join(unread)}.")
        out.append("-- Anything they would have provided is missing or '?' below -- "
                   "absence here does NOT mean absence in the database.")
        out.append("")
    ntab = nview = 0
    for schema, name, otype, remarks in sorted(
            (s(o[0]), s(o[1]), s(o[2]), s(o[3])) for o in data["objects"]):
        cols = by_col.get((schema, name), [])
        is_view = otype == "V"
        pkmap = by_pk.get((schema, name), {})

        defs = []
        for c in cols:
            cname = s(c[2])
            nulls = s(c[6]).upper()
            null_txt = (" NOT NULL" if nulls in ("N", "NO")
                        else "" if nulls in ("Y", "YES") else " /*null:?*/")
            defs.append(f'{q(cname)} {eng.fmt_type(c)}{null_txt}')
        if not cols:
            defs.append("/* columns:? */")

        if pkmap:
            pk_cols = [n for n, _ in sorted(pkmap.items(), key=lambda kv: kv[1])]
        else:
            pk_cols = [s(c[2]) for c in sorted(
                (c for c in cols if c[7] not in (None, "")), key=lambda c: int(c[7]))]
        if pk_cols:
            defs.append("PRIMARY KEY (" + ", ".join(q(c) for c in pk_cols) + ")")
        elif not is_view and not data["ok"]["pk"]:
            # We could not read the key catalog -- say so instead of implying none.
            defs.append("/* PRIMARY KEY:? */")

        kind = "VIEW" if is_view else "TABLE"
        tail = f"  -- {remarks}" if remarks else ""
        if is_view:
            nview += 1
            dep = sorted({q(s(d[2]), s(d[3])) for d in by_dep.get((schema, name), [])})
            dep_txt = ", ".join(dep) if dep else ("?" if not data["ok"]["viewdeps"] else "none")
            tail = f"{tail}  -- depends on: {dep_txt}"
        else:
            ntab += 1
        out.append(f'CREATE {kind} {q(schema, name)} ({", ".join(defs)});{tail}')

        for c in cols:
            if s(c[8]):
                out.append(f"COMMENT ON COLUMN {q(schema, name, s(c[2]))} "
                           f"IS '{esc(s(c[8]))}';")
        if not is_view and not data["ok"]["indexes"]:
            # No index lines follow for this table -- say why, per table, so a grep
            # for the table name shows it. Otherwise "no indexes" is a silent lie.
            out.append(f"-- INDEXES:? {q(schema, name)} -- index catalog not readable")
        if not is_view:
            for i in by_idx.get((schema, name), []):
                iname = s(i[2])
                sep = by_ixc.get((schema, name, iname))
                icols = ([c for _, c in sorted(sep)] if sep
                         else eng.split_index_cols(s(i[4])))
                uniq = "UNIQUE " if s(i[3]) in ("U", "P", "UNIQUE") else ""
                cols_txt = ", ".join(icols) if icols else "/* columns:? */"
                out.append(f"CREATE {uniq}INDEX {q(schema, iname)} "
                           f"ON {q(schema, name)} ({cols_txt});")
    return out, ntab, nview


# ----------------------------------------------------------------- commands
def cmd_test(alias: str) -> int:
    prof = load_profile(alias)
    eng = ENGINES[prof["DB_TYPE"]]
    t0 = time.time()
    conn = eng.connect(prof)
    cur = conn.cursor()
    cur.execute(eng.ping_sql)
    row = cur.fetchone()
    ms = (time.time() - t0) * 1000
    cur.close()
    conn.close()
    ok = bool(row) and int(row[0]) == 1
    print(f"{'OK' if ok else 'FAIL'}  {safe_dsn(prof)}  driver={eng.driver}  "
          f"`{eng.ping_sql}` -> {tuple(row) if row else row}  ({ms:.0f} ms)")
    return 0 if ok else 1


def cmd_query(alias: str, sql: str, fmt: str) -> int:
    prof = load_profile(alias)
    eng = ENGINES[prof["DB_TYPE"]]
    conn = eng.connect(prof)
    cur = conn.cursor()
    cur.execute(sql)
    if cur.description is None:            # DDL/DML: nothing to print
        conn.commit()
        print("OK (no result set)")
        cur.close()
        conn.close()
        return 0
    head = [d[0] for d in cur.description]
    data = [tuple(r) for r in cur.fetchall()]
    cur.close()
    conn.close()

    if fmt == "csv":
        w = csv.writer(sys.stdout, lineterminator="\n")
        w.writerow(head)
        w.writerows(data)
    elif fmt == "json":
        print(json.dumps([dict(zip(head, r)) for r in data],
                         ensure_ascii=False, default=str, indent=2))
    else:
        cells = [[("" if v is None else str(v)) for v in r] for r in data]
        width = [max(len(head[i]), *(len(r[i]) for r in cells)) if cells else len(head[i])
                 for i in range(len(head))]
        line = "-+-".join("-" * w for w in width)
        print(" | ".join(h.ljust(width[i]) for i, h in enumerate(head)))
        print(line)
        for r in cells:
            print(" | ".join(c.ljust(width[i]) for i, c in enumerate(r)))
        print(f"({len(data)} row{'' if len(data) == 1 else 's'})")
    return 0


def cmd_dump(alias: str) -> int:
    prof = load_profile(alias)
    eng = ENGINES[prof["DB_TYPE"]]
    conn = eng.connect(prof)
    cur = conn.cursor()
    data, ok = {}, {}
    for key in ("objects", "columns", "indexes", "viewdeps", "pk", "idxcols"):
        data[key], ok[key] = rows(cur, getattr(eng, key))
    # Engines that carry key/index order inside the column catalog have no separate
    # query; their trustworthiness is that of the query that did run.
    if eng.pk is None:
        ok["pk"] = ok["columns"]
    if eng.idxcols is None:
        ok["idxcols"] = ok["indexes"]
    data["ok"] = ok
    cur.close()
    conn.close()

    lines, ntab, nview = render(eng, data, alias, prof)
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    outfile = SCHEMA_DIR / f"{alias}.schema.sql"
    outfile.write_text("\n".join(lines) + "\n", encoding="utf-8")

    size = outfile.stat().st_size
    print(f"Dumped {ntab} tables, {nview} views -> {outfile} ({size} bytes)")
    bad = sorted(k for k, v in ok.items() if not v)
    if bad:
        print(f"WARN: could not read: {', '.join(bad)} -- those values are '?' "
              f"in the dump, which is not the same as 'none'.")
    # 0 objects can mean "empty schema" or "could not read the catalog". Not the same.
    if ntab == 0 and nview == 0:
        if ok["objects"]:
            print("NOTE: 0 objects, but the catalog read fine -- the schema is empty "
                  "(or your account sees nothing in it).")
        else:
            print("ERROR: 0 objects because the catalog could NOT be read. "
                  "This is not an empty schema.")
            return 1
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Schema dump for engines usql cannot introspect safely (Db2, Oracle)")
    ap.add_argument("cmd", choices=("test", "query", "dump"))
    ap.add_argument("alias")
    ap.add_argument("sql", nargs="?", default=None)
    ap.add_argument("fmt", nargs="?", default="table",
                    choices=("table", "csv", "json"))
    a = ap.parse_args(argv)
    prof = load_profile(a.alias)
    if prof.get("DB_TYPE") not in ENGINES:
        sys.exit(f"ERROR: db_schema.py handles {'/'.join(sorted(ENGINES))}, "
                 f"not '{prof.get('DB_TYPE')}'. Use db.sh for that type.")
    if a.cmd == "test":
        return cmd_test(a.alias)
    if a.cmd == "query":
        if not a.sql:
            sys.exit('Usage: db_schema.py query <alias> "<sql>" [table|csv|json]')
        return cmd_query(a.alias, a.sql, a.fmt)
    return cmd_dump(a.alias)


if __name__ == "__main__":
    raise SystemExit(main())
